### PR TITLE
Add maven-publish.gradle to enable publishing to GitLab

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Review by schildbach — APPROVED** [review]

**Comment by msgilligan** [comment]
This is DRAFT, because I want to see if I can change `allprojects` back to `subprojects`.

**Comment by msgilligan** [comment]
> This is DRAFT, because I want to see if I can change `allprojects` back to `subprojects`.

This has been fixed and force-pushed.

I also added `ext.publishedProjects = ['secp-api', 'secp-ffm', 'secp-bouncy']` so that only the three main libraries are published to Maven.

**Review by schildbach — APPROVED** [review]
In the specific case of GitLab actions, it makes sense to link to a CI run of your branch at GitLab, so I can look at the logs and the build artifacts.

**Comment by msgilligan** [comment]
> In the specific case of GitLab actions, it makes sense to link to a CI run of your branch at GitLab, so I can look at the logs and the build artifacts.

I haven't added GitLab CI yet. I'm just going to publish to GitLab's project-level Maven repository. We should add GitLab CI in the future.

**Pull request merged**
